version: "3.8"

services:
  frontend:
    image: frontend_image
    ports:
      - "3000:3000"
    networks:
      - front-tier



  backend:
    image: backend 
    volumes:
     - backend_data:/usr/src/app
    depends_on:
      - mongo
    networks:
       - front-tier
       - back-tier
    ports:
      - "3001:3001"

  
  mongo:
    image: mongo
    restart: always
    volumes:
    - /home/aman/Downloads/LocalDB:/data/db
    environment: 
      - "MONGODB_INITDB_ROOT_USERNAME:username"
      - "MONGODB_INITDB_ROOT_PASSWORD:password"
    networks: 
      - back-tier

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - frontend
      - backend
    volumes:
      - /home/aman/projects/DevOps/composeTask/docker-frontend-backend-db-master/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      - front-tier
      - back-tier

volumes:
  backend_data:

networks:
  front-tier:
  back-tier:
